---
- name: install traefik
  get_url: dest={{ traefik_bin_path }} checksum={{ traefik_hash }} owner=root group=root mode=0755
    url={{ traefik_binary_url }}
  notify:
    - restart traefik

- name: create traefik user
  user: name=traefik groups=docker system=yes shell=/bin/false create_home=no

- name: create systemd service unit
  template: src={{ traefik_systemd_unit }} dest=/etc/systemd/system/traefik.service
    owner=root group=root
  notify:
    - reload systemd
    - restart traefik

- name: enable traefik service
  service: name=traefik enabled=yes

- name: copy traefik config
  template: src={{ traefik_config_template }} dest=/etc/traefik.toml owner=root group=root
  notify:
    - restart traefik

- name: create traefik work directory
  file: path=/var/lib/traefik state=directory owner=root group=root mode=0750
