---
- name: retrieve current traefik installation
  stat:
    path: "{{ traefik_bin_path }}"
    checksum_algorithm: "{{ traefik_hash | regex_search('^(.*?)(?=:)') }}"
    get_checksum: yes
    get_attributes: no
    get_mime: no
  register: traefik_bin_stat

- name: install traefik
  include_tasks: install.yml
  when:
    - not ansible_check_mode
    - traefik_bin_stat.stat.checksum is not defined or traefik_bin_stat.stat.checksum != traefik_hash|regex_search('[a-fA-F0-9]+$')

- name: create traefik user
  user: name=traefik groups=docker system=yes shell=/bin/false create_home=no

- name: create traefik config directory
  file: path={{ traefik_conf_path | dirname }} state=directory owner=traefik group=traefik mode=0750

- name: create traefik acme directory
  file: path={{ traefik_acme_path | dirname }} state=directory owner=traefik group=traefik mode=0750

- name: copy traefik config
  template: src={{ traefik_config_template }} dest={{ traefik_conf_path }} owner=root group=root
  notify:
    - restart traefik

- name: create systemd service unit
  template: src={{ traefik_systemd_unit }} dest=/etc/systemd/system/traefik.service
    owner=root group=root
  notify:
    - reload systemd
    - restart traefik

- name: enable traefik service
  service: name=traefik enabled=yes
